Arm module
SaintsRobotics/ChargedUp2023 pull request #16
Opened 2023-02-18 06:34 UTC by ReeledWarrior14

2023-02-18 18:48 UTC, LeonardAbbas requested changes
Since `DriveElevatorCommand` and `PivotArmCommand` require the same subsystem, they can't be run at the same time, which is inefficient. Instead we could remove both commands and add methods in the subsystem for controlling the elevator and pivot.

Also needs some organization, and since we don't have a bot to test it on, I don't think there's any point to merging this now.

2023-02-20 06:11 UTC, ReeledWarrior14 commented
For the arm we will use 4 limit switches on the elevator and an encoder for the pivot. The 4 limit switches will be placed in:
1. Resting position - Where the arm will be moved to IMMEDIATLY at the beginning of the match and never go past this point
2. Mid node position - Where the arm will need to be to place an object on a mid node
3. High node position - Where the arm will need to be to place an object on a high node
4. Station pickup position - Where the arm will need to be to pick an object up from the pickup station

We will drive the arm between these setpoints at a constant motor speed rather than a PID controller (because we do not have exact values required for the PID controller). 

These controls should be on the Operator Controller's D-Pad (ie. back for resting position, front for station pickup...)

2023-02-20 06:39 UTC, ReeledWarrior14 commented
Note: Limit switches will be `DigitalInput` objects from WPILib

2023-02-22 00:57 UTC, LeonardAbbas requested changes
still needs a bunch of formatting

2023-02-22 00:57 UTC, LeonardAbbas commented on src/main/java/frc/robot/RobotContainer.java
> +    // m_armSubsystem.setDefaultCommand();
should be removed

2023-02-22 00:57 UTC, LeonardAbbas commented on src/main/java/frc/robot/commands/ArmCommand.java
> +    m_pivotSetpoint = pivotSetpoint;
intead of having `m_pivotSetpoint` and `m_elevatorSetpoint` just call `PIDController.setSetpoint`

2023-02-22 00:57 UTC, LeonardAbbas commented on src/main/java/frc/robot/commands/ArmCommand.java
> +// 19 --> 26 (turn)
remove

2023-02-22 00:57 UTC, LeonardAbbas commented on src/main/java/frc/robot/commands/ArmCommand.java
> +    // Use addRequirements() here to declare subsystem dependencies.
get rid of all these useless comments

2023-02-22 00:57 UTC, LeonardAbbas commented on src/main/java/frc/robot/subsystems/ArmSubsystem.java
> +  private double m_pivotSpeed;
no need to have this saved as a double, just call `m_pivotMotor.set(m_pivotSpeed);` in the method `setPivotSpeed` instead of `periodic`

2023-02-24 22:27 UTC, mebrahimaleem commented
The issues LeonardAbbas pointed out have been resolved. Branch is also ready for testing.

2023-02-25 23:44 UTC, LeonardAbbas reviewed
there's a lot of logic going on in the subsystem, which could be simplified if we move some of it into a command. ie. the subsystem would have a method for setting the speeds of the elevator and pivot motors while a command has the PID controllers for driving the motors to a position. I think this would work a lot better. I can talk more about what I mean on monday's meeting.

2023-02-25 23:59 UTC, ReeledWarrior14 commented
Thanks Lenny!

2023-02-27 05:52 UTC, ReeledWarrior14 commented
This PR has working elevator code. Tomorrow a new branch and PR will be made for pivot code. We are merging what we have working at the moment.

2023-02-28 01:48 UTC, merged